version: '{build}'
os: Visual Studio 2015
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: U8vpVdaIAWQFmqDfHb8nT0aDMUVqVf/w/CMlDVcp1f7zWVqRtNXwwKM/9+SJ/t6A
install:
- ps: >-
    nuget update -self

    nuget sources add -Name netcore -Source http://myget.org/F/dotnet-core

    Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview1/scripts/obtain/dotnet-install.ps1" -OutFile ".\dotnet-install.ps1"

    $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"

    & .\dotnet-install.ps1 -Channel "preview" -Version "1.0.0-beta-002071" -InstallDir "$env:DOTNET_INSTALL_DIR"

build: off
test_script:
- ps: dotnet restore
- ps: ./Coverage.ps1
